### PR TITLE
Disable pruning if wanted and add more tests/coverage

### PR DESCRIPTION
**Pull request by mehdidc**
- add enable_pruning parameter to avoid pruning if wanted
- raise NotFittedError in predict, transform, predict_deriv, score when the model is not fitted
- raise ValueError if the length of xlabels is not the same as the number of columns
- add pyearth.test.basis and pyearth.test.record modules to setup.py
- add test data to MANIFEST.in
- increase coverage of earth.py by adding more tests in pyearth/test/test_earth.py
- Fixed an error when max_terms was set to 1

### CODE REVIEW

**Comment by jcrudy** [comment]
Looks great.  I really appreciate all the detailed attention you've put into this.  A few questions:

1. It appears that this breaks compatibility with sklearn versions <0.16 because of check_is_fitted (and possibly other utilities?).  I think it would make sense to include substitute functions to emulate those utilities if they fail to import (for compatibility with older versions), but I'd appreciate your input on this as I think you know more about sklearn than I do.  Is it important to support older versions?  If so, what's the best way?  If not, I guess there is something we can add to setup.py to specify the version dependence?

2. When I run the tests, I see a bunch of DataConversionWarnings:

        DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().  y = column_or_1d(y, warn=True)

Is this expected and correct behavior?  If so, should we change the tests to either catch or not produce these warnings?

**Comment by mehdidc** [comment]
For 1, I am not sure either, I would say we can add add a >=0.16 requirement in setup.py, but it's true the only reason why we require scikit learn >= 0.16  is only for check_X_y and check_fitted,  @agramfort do you think it is better to add wrappers to check_X_y and check_fitted ? 

For 2, there is a  warning because check_X_y is expecting a vector for y while a matrix is passed, the warning will disappear by adding multi_column=True to check_X_y

**Comment by agramfort** [comment]
I think it's fine to depend on latest release scikit-learn version for
py-earth

if you need unreleased functions you need to backport

**Comment by jcrudy** [comment]
Thank you!  Merged into master.  Updated to depend on scikit-learn >= 0.16 and used multi_output=True to eliminate warnings.

**Pull request merged**
