### PR TITLE
small fixes to pass scikit-learn check_estimator

### PR DESCRIPTION
**Pull request by mehdidc**
Small fixes needed to pass scikit-learn check_estimator (http://scikit-learn.org/stable/modules/generated/sklearn.utils.estimator_checks.check_estimator.html)  for scikit-learn-contrib (https://github.com/scikit-learn-contrib/scikit-learn-contrib/blob/master/workflow.md). 

The reason behind the modifications of pyearth/earth.py is to handle the case when X is a list rather than np.array because check_estimator require that the Estimator works in that case. if X is a list rather than np.array then np.isnan(X) throws an exception ("TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe'") for some reason... so it is why X = np.arrray(..)  was moved.

### CODE REVIEW

**Comment by jcrudy** [comment]
Thanks again, @mehdidc.  I've merged this as well.  I'm going to add a test with check_estimator.

**Comment by mehdidc** [comment]
Great! one thing about check_estimator, I actually had to change (https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/utils/estimator_checks.py) to make the test pass, but that's more a scikit-learn issue I would say, so in that file if the name of the class is not in MULTI_OUTPUT the test does not pass because it assumes that Earth only deals with 1D outputs, so what I did was just adding 'Earth' to MULTI_OUTPUT.

**Comment by jcrudy** [comment]
Oh, I just hit that same problem.  Thanks for that.  I added `'Earth'` to `MULTI_OUTPUT` in the test.  Although it still doesn't pass because there is a bug in check_estimator.  When I fix the bug it passes.  However, it looks like the bug still exists in sklearn 0.17.1.  It's only been fixed in master.  So, I'm going to have my test skip for now.  Once sklearn is fixed we can set it to run automatically.

I noticed we have a test failure now on travis for `test_missing_data`.  I don't see this failure when I test on my system.  Do you see it?  In any case, I'm going to try to rewrite the test to be less brittle.

**Comment by mehdidc** [comment]
Yes, I see it, here is the exception I get :
`
 File "/home/mehdi/work/code/py-earth/pyearth/test/test_earth.py", line 148, in test_missing_data
    assert_almost_equal(float(res), float(prev))
AssertionError: 0.426621205253 != 0.494056424921 within 7 places
`

**Comment by jcrudy** [comment]
That's even worse than on travis.  I wonder what is causing this variation on different systems.  In any case, since I fixed many bugs in missing data handling in the `rewrite_forward_pass` branch we should wait until after merging to worry about this.

**Pull request merged**
